services:
  - type: web
    name: study-mate-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ACCESS_JWT_EXPIRES_IN
        sync: false # sync=false means youâ€™ll enter value in Render dashboard
      - key: ACCESS_JWT_SECRET
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_URL
        sync: false
      - key: FIREBASE_SDK_API_KEY
        sync: false
      - key: PORT
        sync: false
        repo: https://github.com/pcb951/study-mate-api.git
        branch: main
